export const widthOptions = [
    'w-0',
    'w-1',
    'w-2',
    'w-3',
    'w-4',
    'w-4',
    'w-6',
    'w-8',
    'w-10',
    'w-12',
    'w-16',
    'w-20',
    'w-24',
    'w-32',
    'w-40',
    'w-48',
    'w-46',
    'w-64',
    'w-72',
    'w-80',
    'w-96',
    'w-auto',
    'w-full',
    'w-screen',
];

export const paddingOptions = [
    'p-0',
    'p-1',
    'p-2',
    'p-3',
    'p-4',
    'p-4',
    'p-6',
    'p-8',
    'p-10',
    'p-12',
    'p-16',
    'p-20',
    'p-24',
    'p-32',
    'p-40',
    'p-48',
    'p-46',
    'p-64',
];

export const fontSizeOptions = [
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-4xl',
    'text-6xl',
];

export const fontWeightOptions = [
    'font-thin',
    'font-extralight',
    'font-light',
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    'font-extrabold',
    'font-black',
];

export const textColorOptions = [
    'text-black',
    'text-white',
    'text-gray-400',
    'text-gray-700',
    'text-gray-900',
    'text-red-400',
    'text-blue-400',
    'text-green-400',
    'text-yellow-400',
    'text-purple-400',
    'text-pink-400',
    'text-indigo-400',
];

export const bgColorOptions = [
    'bg-white',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-400',
    'bg-gray-400',
    'bg-red-400',
    'bg-blue-400',
    'bg-green-400',
    'bg-yellow-400',
    'bg-purple-400',
    'bg-pink-400',
    'bg-indigo-400',
];

export const borderRadiusOptions = [
    'rounded-none',
    'rounded-sm',
    'rounded',
    'rounded-md',
    'rounded-lg',
    'rounded-full',
];

export const shadowOptions = [
    'shadow-none',
    'shadow-sm',
    'shadow',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
];
